form = document.getElementById('number-form');
selectCountries = document.getElementById('select-countries')
phoneNumber = document.getElementById('phone-number');
submit = document.getElementById('submit');

function addCountries() {
    for (let i = 0; i < countries.length; i++) {
        selectCountries.innerHTML += `<option id="select-country" value="${countries[i].phone}"> ${countries[i].name} (+${Number(countries[i].phone)})</option>`
    }
}

phoneNumber.addEventListener('keypress', (e) => maskPhoneNumber(e.target.value)) // Dispara quando digitado no campo
phoneNumber.addEventListener('change', (e) => maskPhoneNumber(e.target.value)) // Dispara quando autocompletado o campo

const maskPhoneNumber = (valor) => {
    valor = valor.replace(/\D/g, "")
    valor = valor.replace(/^(\d{2})(\d)/g, "($1) $2")
    valor = valor.replace(/(\d)(\d{4})$/, "$1-$2")
    phoneNumber.value = valor // Insere o(s) valor(es) no campo
}

function submitForm(){
    form.submit();
}

function callNumber() {
    const numberCleaned = phoneNumber.value.replace(/\D/g, '');
    // `https://web.whatsapp.com/send?phone=${selectCountries.value + phoneNumber.value}&type=phone_number&app_absent=0`
    let newUrl = `https://wa.me/${Number(selectCountries.value + numberCleaned)}`;
    console.log(newUrl);
    submit.href = newUrl    // location.replace(newUrl)
}


countries = [
    { "code": "004", "phone": "0093", "iso": "AF", "iso3": "AFG", "name": "Afeganistão", "formalName": "República Islâmica do Afeganistão" },
    { "code": "008", "phone": "0355", "iso": "AL", "iso3": "ALB", "name": "Albânia", "formalName": "República da Albânia" },
    { "code": "012", "phone": "0213", "iso": "DZ", "iso3": "DZA", "name": "Algéria", "formalName": "República Democrática Popular da Algéria" },
    { "code": "016", "phone": "1684", "iso": "AS", "iso3": "ASM", "name": "Samoa Americana", "formalName": "Território de Samoa Americana" },
    { "code": "020", "phone": "0376", "iso": "AD", "iso3": "AND", "name": "Andorra", "formalName": "Principado Andorra" },
    { "code": "024", "phone": "0244", "iso": "AO", "iso3": "AGO", "name": "Angola", "formalName": "República de Angola" },
    { "code": "660", "phone": "1264", "iso": "AI", "iso3": "AIA", "name": "Anguilla", "formalName": "Anguilla" },
    { "code": "010", "phone": "0672", "iso": "AQ", "iso3": "ATA", "name": "Antártida", "formalName": "Antártida" },
    { "code": "028", "phone": "1268", "iso": "AG", "iso3": "ATG", "name": "Antigua e Barbuda", "formalName": "Antigua e Barbuda" },
    { "code": "032", "phone": "0054", "iso": "AR", "iso3": "ARG", "name": "Argentina", "formalName": "República Argentina" },
    { "code": "051", "phone": "0374", "iso": "AM", "iso3": "ARM", "name": "Armênia", "formalName": "República da Armênia" },
    { "code": "533", "phone": "0297", "iso": "AW", "iso3": "ABW", "name": "Aruba", "formalName": "Aruba" },
    { "code": "036", "phone": "0061", "iso": "AU", "iso3": "AUS", "name": "Austrália", "formalName": "Comunidade da Austrália" },
    { "code": "040", "phone": "0043", "iso": "AT", "iso3": "AUT", "name": "Áustria", "formalName": "República da Áustria" },
    { "code": "031", "phone": "0994", "iso": "AZ", "iso3": "AZE", "name": "Azerbaijão", "formalName": "República do Azerbaijão" },
    { "code": "044", "phone": "1242", "iso": "BS", "iso3": "BHS", "name": "Bahamas", "formalName": "Comunidade de Bahamas" },
    { "code": "048", "phone": "0973", "iso": "BH", "iso3": "BHR", "name": "Bahrein", "formalName": "Reino do Bahrein" },
    { "code": "050", "phone": "0880", "iso": "BD", "iso3": "BGD", "name": "Bangladesh", "formalName": "República Popular de Bangladesh" },
    { "code": "052", "phone": "0246", "iso": "BB", "iso3": "BRB", "name": "Barbados", "formalName": "Barbados" },
    { "code": "112", "phone": "0375", "iso": "BY", "iso3": "BLR", "name": "Bielorrússia", "formalName": "República da Bielorrússia" },
    { "code": "056", "phone": "0032", "iso": "BE", "iso3": "BEL", "name": "Bélgica", "formalName": "Reino da Bélgica" },
    { "code": "084", "phone": "0501", "iso": "BZ", "iso3": "BLZ", "name": "Belize", "formalName": "Belize" },
    { "code": "204", "phone": "0229", "iso": "BJ", "iso3": "BEN", "name": "Benin", "formalName": "República do Benin" },
    { "code": "060", "phone": "1441", "iso": "BM", "iso3": "BMU", "name": "Bermuda", "formalName": "Bermuda" },
    { "code": "064", "phone": "0975", "iso": "BT", "iso3": "BTN", "name": "Butão", "formalName": "Reino do Butão" },
    { "code": "068", "phone": "0591", "iso": "BO", "iso3": "BOL", "name": "Bolívia", "formalName": "Estado Plurinacional da Bolívia" },
    { "code": "070", "phone": "0387", "iso": "BA", "iso3": "BIH", "name": "Bósnia e Herzegovina", "formalName": "Bósnia e Herzegovina" },
    { "code": "072", "phone": "0267", "iso": "BW", "iso3": "BWA", "name": "Botswana", "formalName": "República da Botswana" },
    { "code": "074", "phone": "0047", "iso": "BV", "iso3": "BVT", "name": "Ilha Bouvet", "formalName": "Ilha Bouvet" },
    { "code": "076", "phone": "0055", "iso": "BR", "iso3": "BRA", "name": "Brasil", "formalName": "República Federativa do Brasil" },
    { "code": "086", "phone": "0246", "iso": "IO", "iso3": "IOT", "name": "Território Britânico do Oceano Índico", "formalName": "Território Britânico do Oceano Índico" },
    { "code": "096", "phone": "0673", "iso": "BN", "iso3": "BRN", "name": "Brunei", "formalName": "Estado do Brunei Darussalam" },
    { "code": "100", "phone": "0359", "iso": "BG", "iso3": "BGR", "name": "Bulgária", "formalName": "República da Bulgária" },
    { "code": "854", "phone": "0226", "iso": "BF", "iso3": "BFA", "name": "Burkina Faso", "formalName": "Burkina Faso" },
    { "code": "108", "phone": "0257", "iso": "BI", "iso3": "BDI", "name": "Burundi", "formalName": "República do Burundi" },
    { "code": "116", "phone": "0855", "iso": "KH", "iso3": "KHM", "name": "Camboja", "formalName": "Reino do Camboja" },
    { "code": "120", "phone": "0237", "iso": "CM", "iso3": "CMR", "name": "Camarões", "formalName": "República de Camarões" },
    { "code": "124", "phone": "0001", "iso": "CA", "iso3": "CAN", "name": "Canadá", "formalName": "Canadá" },
    { "code": "132", "phone": "0238", "iso": "CV", "iso3": "CPV", "name": "Cabo Verde", "formalName": "República do Cabo Verde" },
    { "code": "136", "phone": "1345", "iso": "KY", "iso3": "CYM", "name": "Ilhas Cayman", "formalName": "Ilhas Cayman" },
    { "code": "140", "phone": "0236", "iso": "CF", "iso3": "CAF", "name": "República Centro-Africana", "formalName": "República Centro-Africana" },
    { "code": "148", "phone": "0235", "iso": "TD", "iso3": "TCD", "name": "Chade", "formalName": "República do Chade" },
    { "code": "152", "phone": "0056", "iso": "CL", "iso3": "CHL", "name": "Chile", "formalName": "República do Chile" },
    { "code": "156", "phone": "0086", "iso": "CN", "iso3": "CHN", "name": "China", "formalName": "República Popular da China" },
    { "code": "162", "phone": "0061", "iso": "CX", "iso3": "CXR", "name": "Ilha Christmas", "formalName": "Território da Ilha Christmas" },
    { "code": "166", "phone": "0672", "iso": "CC", "iso3": "CCK", "name": "Ilhas Cocos (Keeling)", "formalName": "Território das Ilhas Cocos (Keeling)" },
    { "code": "170", "phone": "0057", "iso": "CO", "iso3": "COL", "name": "Colômbia", "formalName": "República da Colômbia" },
    { "code": "174", "phone": "0269", "iso": "KM", "iso3": "COM", "name": "Comores", "formalName": "União das Comores" },
    { "code": "178", "phone": "0242", "iso": "CG", "iso3": "COG", "name": "Congo", "formalName": "República do Congo" },
    { "code": "180", "phone": "0242", "iso": "CD", "iso3": "COD", "name": "Congo (DR)", "formalName": "República Democrática do Congo" },
    { "code": "184", "phone": "0682", "iso": "CK", "iso3": "COK", "name": "Ilhas Cook", "formalName": "Ilhas Cook" },
    { "code": "188", "phone": "0506", "iso": "CR", "iso3": "CRI", "name": "Costa Rica", "formalName": "República da Costa Rica" },
    { "code": "384", "phone": "0225", "iso": "CI", "iso3": "CIV", "name": "Costa do Marfim", "formalName": "República da Costa do Marfim" },
    { "code": "191", "phone": "0385", "iso": "HR", "iso3": "HRV", "name": "Croácia", "formalName": "República da Croácia" },
    { "code": "192", "phone": "0053", "iso": "CU", "iso3": "CUB", "name": "Cuba", "formalName": "República de Cuba" },
    { "code": "196", "phone": "0357", "iso": "CY", "iso3": "CYP", "name": "Chipre", "formalName": "República do Chipre" },
    { "code": "203", "phone": "0420", "iso": "CZ", "iso3": "CZE", "name": "República Tcheca", "formalName": "República Tcheca" },
    { "code": "208", "phone": "0045", "iso": "DK", "iso3": "DNK", "name": "Dinamarca", "formalName": "Reino da Dinamarca" },
    { "code": "262", "phone": "0253", "iso": "DJ", "iso3": "DJI", "name": "Djibuti", "formalName": "República do Djibuti" },
    { "code": "212", "phone": "1767", "iso": "DM", "iso3": "DMA", "name": "Dominica", "formalName": "Comunidade da Dominica" },
    { "code": "214", "phone": "1809", "iso": "DO", "iso3": "DOM", "name": "República Dominicana", "formalName": "República Dominicana" },
    { "code": "218", "phone": "0593", "iso": "EC", "iso3": "ECU", "name": "Equador", "formalName": "República do Equador" },
    { "code": "818", "phone": "0020", "iso": "EG", "iso3": "EGY", "name": "Egito", "formalName": "República Árabe do Egito" },
    { "code": "222", "phone": "0503", "iso": "SV", "iso3": "SLV", "name": "El Salvador", "formalName": "República El Salvador" },
    { "code": "226", "phone": "0240", "iso": "GQ", "iso3": "GNQ", "name": "Guiné Equatorial", "formalName": "República do Guiné Equatorial" },
    { "code": "232", "phone": "0291", "iso": "ER", "iso3": "ERI", "name": "Eritreia", "formalName": "Estado da Eritreia" },
    { "code": "233", "phone": "0372", "iso": "EE", "iso3": "EST", "name": "Estônia", "formalName": "República da Estônia" },
    { "code": "231", "phone": "0251", "iso": "ET", "iso3": "ETH", "name": "Etiópia", "formalName": "República Democrática Federal da Etiópia" },
    { "code": "238", "phone": "0500", "iso": "FK", "iso3": "FLK", "name": "Ilhas Malvinas", "formalName": "Ilhas Malvinas" },
    { "code": "234", "phone": "0298", "iso": "FO", "iso3": "FRO", "name": "Ilhas Faroe", "formalName": "Ilhas Faroe" },
    { "code": "242", "phone": "0679", "iso": "FJ", "iso3": "FJI", "name": "Fiji", "formalName": "República do Fiji" },
    { "code": "246", "phone": "0358", "iso": "FI", "iso3": "FIN", "name": "Finlândia", "formalName": "República da Finlândia" },
    { "code": "250", "phone": "0033", "iso": "FR", "iso3": "FRA", "name": "França", "formalName": "República Francesa" },
    { "code": "254", "phone": "0594", "iso": "GF", "iso3": "GUF", "name": "Guiana Francesa", "formalName": "Guiana Francesa" },
    { "code": "258", "phone": "0689", "iso": "PF", "iso3": "PYF", "name": "Polinésia Francesa", "formalName": "Polinésia Francesa" },
    { "code": "260", "phone": "0033", "iso": "TF", "iso3": "ATF", "name": "Terras Austrais e Antárticas Francesas", "formalName": "Território das Terras Austrais e Antárticas Francesas" },
    { "code": "266", "phone": "0241", "iso": "GA", "iso3": "GAB", "name": "Gabão", "formalName": "República Gabonesa" },
    { "code": "270", "phone": "0220", "iso": "GM", "iso3": "GMB", "name": "Gâmbia", "formalName": "República da Gâmbia" },
    { "code": "268", "phone": "0995", "iso": "GE", "iso3": "GEO", "name": "Geórgia", "formalName": "Geórgia" },
    { "code": "276", "phone": "0049", "iso": "DE", "iso3": "DEU", "name": "Alemanha", "formalName": "República Federal da Alemanha" },
    { "code": "288", "phone": "0233", "iso": "GH", "iso3": "GHA", "name": "Gana", "formalName": "Repúblia de Gana" },
    { "code": "292", "phone": "0350", "iso": "GI", "iso3": "GIB", "name": "Gibraltar", "formalName": "Gibraltar" },
    { "code": "300", "phone": "0030", "iso": "GR", "iso3": "GRC", "name": "Grécia", "formalName": "República Helênica" },
    { "code": "304", "phone": "0299", "iso": "GL", "iso3": "GRL", "name": "Groelândia", "formalName": "Groelândia" },
    { "code": "308", "phone": "1473", "iso": "GD", "iso3": "GRD", "name": "Granada", "formalName": "Granada" },
    { "code": "312", "phone": "0590", "iso": "GP", "iso3": "GLP", "name": "Guadalupe", "formalName": "Guadalupe" },
    { "code": "316", "phone": "1671", "iso": "GU", "iso3": "GUM", "name": "Guão", "formalName": "Território do Guão" },
    { "code": "320", "phone": "0502", "iso": "GT", "iso3": "GTM", "name": "Guatemala", "formalName": "República da Guatemala" },
    { "code": "324", "phone": "0224", "iso": "GN", "iso3": "GIN", "name": "Guiné", "formalName": "República do Guiné" },
    { "code": "624", "phone": "0245", "iso": "GW", "iso3": "GNB", "name": "Guiné-Bissau", "formalName": "República da Guiné-Bissau" },
    { "code": "328", "phone": "0592", "iso": "GY", "iso3": "GUY", "name": "Guiana", "formalName": "República Cooperativa da Guiana" },
    { "code": "332", "phone": "0509", "iso": "HT", "iso3": "HTI", "name": "Haiti", "formalName": "República do Haiti" },
    { "code": "334", "phone": "0672", "iso": "HM", "iso3": "HMD", "name": "Ilhas Heard e McDonald", "formalName": "Território das Ilhas Heard e McDonald" },
    { "code": "336", "phone": "0039", "iso": "VA", "iso3": "VAT", "name": "Vaticano", "formalName": "Estado da Cidade do Vaticano" },
    { "code": "340", "phone": "0504", "iso": "HN", "iso3": "HND", "name": "Honduras", "formalName": "República de Honduras" },
    { "code": "344", "phone": "0852", "iso": "HK", "iso3": "HKG", "name": "Hong Kong", "formalName": "Região Administrativa Especial de Hong Kong da República Popular da China" },
    { "code": "348", "phone": "0036", "iso": "HU", "iso3": "HUN", "name": "Hungria", "formalName": "Hungria" },
    { "code": "352", "phone": "0354", "iso": "IS", "iso3": "ISL", "name": "Islândia", "formalName": "Islândia" },
    { "code": "356", "phone": "0091", "iso": "IN", "iso3": "IND", "name": "Índia", "formalName": "República da Índia" },
    { "code": "360", "phone": "0062", "iso": "ID", "iso3": "IDN", "name": "Indonésia", "formalName": "República da Indonésia" },
    { "code": "364", "phone": "0098", "iso": "IR", "iso3": "IRN", "name": "Iran", "formalName": "República Islâmica do Iran" },
    { "code": "368", "phone": "0964", "iso": "IQ", "iso3": "IRQ", "name": "Iraque", "formalName": "República do Iraque" },
    { "code": "372", "phone": "0353", "iso": "IE", "iso3": "IRL", "name": "Irlanda", "formalName": "Irlanda" },
    { "code": "376", "phone": "0972", "iso": "IL", "iso3": "ISR", "name": "Israel", "formalName": "Estado de Israel" },
    { "code": "380", "phone": "0039", "iso": "IT", "iso3": "ITA", "name": "Itália", "formalName": "República Italiana" },
    { "code": "388", "phone": "1876", "iso": "JM", "iso3": "JAM", "name": "Jamaica", "formalName": "Jamaica" },
    { "code": "392", "phone": "0081", "iso": "JP", "iso3": "JPN", "name": "Japão", "formalName": "Japão" },
    { "code": "400", "phone": "0962", "iso": "JO", "iso3": "JOR", "name": "Jordânia", "formalName": "Reino Hachemita da Jordânia" },
    { "code": "398", "phone": "0007", "iso": "KZ", "iso3": "KAZ", "name": "Cazaquistão", "formalName": "República do Cazaquistão" },
    { "code": "404", "phone": "0254", "iso": "KE", "iso3": "KEN", "name": "Quênia", "formalName": "República do Quênia" },
    { "code": "296", "phone": "0686", "iso": "KI", "iso3": "KIR", "name": "Kiribati", "formalName": "República do Kiribati" },
    { "code": "408", "phone": "0850", "iso": "KP", "iso3": "PRK", "name": "Coreia do Norte", "formalName": "República Democrática Popular da Coreia" },
    { "code": "410", "phone": "0082", "iso": "KR", "iso3": "KOR", "name": "Coreia do Sul", "formalName": "República da Coreia" },
    { "code": "414", "phone": "0965", "iso": "KW", "iso3": "KWT", "name": "Kuwait", "formalName": "Estado do Kuwait" },
    { "code": "417", "phone": "0996", "iso": "KG", "iso3": "KGZ", "name": "Quirguistão", "formalName": "República Quirguiz" },
    { "code": "418", "phone": "0856", "iso": "LA", "iso3": "LAO", "name": "Laos", "formalName": "República Democrática Popular Lau" },
    { "code": "428", "phone": "0371", "iso": "LV", "iso3": "LVA", "name": "Letônia", "formalName": "República da Letônia" },
    { "code": "422", "phone": "0961", "iso": "LB", "iso3": "LBN", "name": "Líbano", "formalName": "República Libanesa" },
    { "code": "426", "phone": "0266", "iso": "LS", "iso3": "LSO", "name": "Lesoto", "formalName": "Reino do Lesoto" },
    { "code": "430", "phone": "0231", "iso": "LR", "iso3": "LBR", "name": "Libéria", "formalName": "República da Libéria" },
    { "code": "434", "phone": "0218", "iso": "LY", "iso3": "LBY", "name": "Líbia", "formalName": "Líbia" },
    { "code": "438", "phone": "0423", "iso": "LI", "iso3": "LIE", "name": "Liechtenstein", "formalName": "Principado de Liechtenstein" },
    { "code": "440", "phone": "0370", "iso": "LT", "iso3": "LTU", "name": "Lituânia", "formalName": "República da Lituânia" },
    { "code": "442", "phone": "0352", "iso": "LU", "iso3": "LUX", "name": "Luxemburgo", "formalName": "Grão-Ducado do Luxemburgo" },
    { "code": "446", "phone": "0853", "iso": "MO", "iso3": "MAC", "name": "Macao", "formalName": "Macao" },
    { "code": "807", "phone": "0389", "iso": "MK", "iso3": "MKD", "name": "Macedônia", "formalName": "República da Macedônia" },
    { "code": "450", "phone": "0261", "iso": "MG", "iso3": "MDG", "name": "Madagascar", "formalName": "República de Madagascar" },
    { "code": "454", "phone": "0265", "iso": "MW", "iso3": "MWI", "name": "Malawi", "formalName": "República de Malawi" },
    { "code": "458", "phone": "0060", "iso": "MY", "iso3": "MYS", "name": "Malásia", "formalName": "Malásia" },
    { "code": "462", "phone": "0960", "iso": "MV", "iso3": "MDV", "name": "Maldivas", "formalName": "Reública de Maldivas" },
    { "code": "466", "phone": "0223", "iso": "ML", "iso3": "MLI", "name": "Mali", "formalName": "República do Mali" },
    { "code": "470", "phone": "0356", "iso": "MT", "iso3": "MLT", "name": "Malta", "formalName": "República de Malta" },
    { "code": "584", "phone": "0692", "iso": "MH", "iso3": "MHL", "name": "Ilhas Marshall", "formalName": "República das Ilhas Marshall" },
    { "code": "474", "phone": "0596", "iso": "MQ", "iso3": "MTQ", "name": "Martinica", "formalName": "Martinica" },
    { "code": "478", "phone": "0222", "iso": "MR", "iso3": "MRT", "name": "Mauritânia", "formalName": "República Islâmica da Mauritânia" },
    { "code": "480", "phone": "0230", "iso": "MU", "iso3": "MUS", "name": "Maurício", "formalName": "República de Maurício" },
    { "code": "175", "phone": "0269", "iso": "YT", "iso3": "MYT", "name": "Mayotte", "formalName": "Departamento de Mayotte" },
    { "code": "484", "phone": "0052", "iso": "MX", "iso3": "MEX", "name": "México", "formalName": "Estados Unidos Mexicanos" },
    { "code": "583", "phone": "0691", "iso": "FM", "iso3": "FSM", "name": "Micronésia", "formalName": "Estados Federados da Micronesia" },
    { "code": "498", "phone": "0373", "iso": "MD", "iso3": "MDA", "name": "Moldova", "formalName": "República de Moldova" },
    { "code": "492", "phone": "0377", "iso": "MC", "iso3": "MCO", "name": "Mônaco", "formalName": "Principado de Mônaco" },
    { "code": "496", "phone": "0976", "iso": "MN", "iso3": "MNG", "name": "Mongólia", "formalName": "Mongólia" },
    { "code": "500", "phone": "1664", "iso": "MS", "iso3": "MSR", "name": "Montserrat", "formalName": "Montserrat" },
    { "code": "504", "phone": "0212", "iso": "MA", "iso3": "MAR", "name": "Marrocos", "formalName": "Reino de Marrocos" },
    { "code": "508", "phone": "0258", "iso": "MZ", "iso3": "MOZ", "name": "Moçambique", "formalName": "República de Moçambique" },
    { "code": "104", "phone": "0095", "iso": "MM", "iso3": "MMR", "name": "Birmânia", "formalName": "República da União de Myanmar" },
    { "code": "516", "phone": "0264", "iso": "NA", "iso3": "NAM", "name": "Namíbia", "formalName": "República da Namíbia" },
    { "code": "520", "phone": "0674", "iso": "NR", "iso3": "NRU", "name": "Nauru", "formalName": "República de Nauru" },
    { "code": "524", "phone": "0977", "iso": "NP", "iso3": "NPL", "name": "Nepal", "formalName": "República Democrática Federativa do Nepal" },
    { "code": "528", "phone": "0031", "iso": "NL", "iso3": "NLD", "name": "Holanda", "formalName": "Holanda" },
    { "code": "530", "phone": "0599", "iso": "AN", "iso3": "ANT", "name": "Antilhas Holandesas", "formalName": "Antilhas Holandesas" },
    { "code": "540", "phone": "0687", "iso": "NC", "iso3": "NCL", "name": "Nova Caledônia", "formalName": "Nova Caledônia" },
    { "code": "554", "phone": "0064", "iso": "NZ", "iso3": "NZL", "name": "Nova Zelândia", "formalName": "Nova Zelândia" },
    { "code": "558", "phone": "0505", "iso": "NI", "iso3": "NIC", "name": "Nicarágua", "formalName": "República da Nicarágua" },
    { "code": "562", "phone": "0227", "iso": "NE", "iso3": "NER", "name": "Niger", "formalName": "República do Niger" },
    { "code": "566", "phone": "0234", "iso": "NG", "iso3": "NGA", "name": "Nigéria", "formalName": "República Federativa da Nigéria" },
    { "code": "570", "phone": "0683", "iso": "NU", "iso3": "NIU", "name": "Niue", "formalName": "Niue" },
    { "code": "574", "phone": "0672", "iso": "NF", "iso3": "NFK", "name": "Ilha Norfolk", "formalName": "Território da Ilha Norfolk" },
    { "code": "580", "phone": "1670", "iso": "MP", "iso3": "MNP", "name": "Ilhas Marianas do Norte", "formalName": "Comunidade das Ilhas Marianas do Norte" },
    { "code": "578", "phone": "0047", "iso": "NO", "iso3": "NOR", "name": "Noruega", "formalName": "Reino da Noruega" },
    { "code": "512", "phone": "0968", "iso": "OM", "iso3": "OMN", "name": "Omã", "formalName": "Sultanato de Omã" },
    { "code": "586", "phone": "0092", "iso": "PK", "iso3": "PAK", "name": "Paquistão", "formalName": "República Islâmica do Paquistão" },
    { "code": "585", "phone": "0680", "iso": "PW", "iso3": "PLW", "name": "Palau", "formalName": "República de Palau" },
    { "code": "275", "phone": "0970", "iso": "PS", "iso3": "PSE", "name": "Palestina", "formalName": "Estado da Palestina" },
    { "code": "591", "phone": "0507", "iso": "PA", "iso3": "PAN", "name": "Panamá", "formalName": "República do Panamá" },
    { "code": "598", "phone": "0675", "iso": "PG", "iso3": "PNG", "name": "Papua-Nova Guiné", "formalName": "Estado Independente da Papua-Nova Guiné" },
    { "code": "600", "phone": "0595", "iso": "PY", "iso3": "PRY", "name": "Paraguai", "formalName": "República do Paraguai" },
    { "code": "604", "phone": "0051", "iso": "PE", "iso3": "PER", "name": "Peru", "formalName": "República do Peru" },
    { "code": "608", "phone": "0063", "iso": "PH", "iso3": "PHL", "name": "Filipinas", "formalName": "República das Filipinas" },
    { "code": "612", "phone": "0672", "iso": "PN", "iso3": "PCN", "name": "Ilhas Picárnia", "formalName": "Ilhas Picárnia" },
    { "code": "616", "phone": "0048", "iso": "PL", "iso3": "POL", "name": "Polônia", "formalName": "República da Polônia" },
    { "code": "620", "phone": "0351", "iso": "PT", "iso3": "PRT", "name": "Portugal", "formalName": "República Portuguesa" },
    { "code": "630", "phone": "1787", "iso": "PR", "iso3": "PRI", "name": "Porto Rico", "formalName": "Comunidade do Porto Rico" },
    { "code": "634", "phone": "0974", "iso": "QA", "iso3": "QAT", "name": "Catar", "formalName": "Estado do Catar" },
    { "code": "638", "phone": "0262", "iso": "RE", "iso3": "REU", "name": "Reunião", "formalName": "Polônia" },
    { "code": "642", "phone": "0040", "iso": "RO", "iso3": "ROM", "name": "Romênia", "formalName": "Romênia" },
    { "code": "643", "phone": "0070", "iso": "RU", "iso3": "RUS", "name": "Rússia", "formalName": "Federação Russa" },
    { "code": "646", "phone": "0250", "iso": "RW", "iso3": "RWA", "name": "Ruanda", "formalName": "República da Ruanda" },
    { "code": "654", "phone": "0290", "iso": "SH", "iso3": "SHN", "name": "Santa Helena", "formalName": "Saint Helena" },
    { "code": "659", "phone": "1869", "iso": "KN", "iso3": "KNA", "name": "São Cristóvão", "formalName": "São Cristóvão" },
    { "code": "662", "phone": "1758", "iso": "LC", "iso3": "LCA", "name": "Santa Lúcia", "formalName": "Santa Lúcia" },
    { "code": "666", "phone": "0508", "iso": "PM", "iso3": "SPM", "name": "São Pedro e Miquelon", "formalName": "Coletividade Territorial de São Pedro e Miquelon" },
    { "code": "670", "phone": "1784", "iso": "VC", "iso3": "VCT", "name": "São Vicente e Granadinas", "formalName": "São Vicente e Granadinas" },
    { "code": "882", "phone": "0684", "iso": "WS", "iso3": "WSM", "name": "Samoa", "formalName": "Estado Independente de Samoa" },
    { "code": "674", "phone": "0378", "iso": "SM", "iso3": "SMR", "name": "São Marino", "formalName": "República de São Marino" },
    { "code": "678", "phone": "0239", "iso": "ST", "iso3": "STP", "name": "Sao Tomé e Príncipe", "formalName": "República Democrática de Sao Tomé e Príncipe" },
    { "code": "682", "phone": "0966", "iso": "SA", "iso3": "SAU", "name": "Arábia Saudita", "formalName": "Reino da Arábia Saudita" },
    { "code": "686", "phone": "0221", "iso": "SN", "iso3": "SEN", "name": "Senegal", "formalName": "República do Senegal" },
    { "code": "688", "phone": "0381", "iso": "CS", "iso3": "SRB", "name": "Sérvia e Montenegro", "formalName": "União Estatal de Sérvia e Montenegro" },
    { "code": "690", "phone": "0248", "iso": "SC", "iso3": "SYC", "name": "Seicheles", "formalName": "República das Seicheles" },
    { "code": "694", "phone": "0232", "iso": "SL", "iso3": "SLE", "name": "República da Serra Leoa", "formalName": "República da Serra Leoa" },
    { "code": "702", "phone": "0065", "iso": "SG", "iso3": "SGP", "name": "Singapura", "formalName": "República da Singapura" },
    { "code": "703", "phone": "0421", "iso": "SK", "iso3": "SVK", "name": "Eslováquia", "formalName": "República Eslovaca" },
    { "code": "705", "phone": "0386", "iso": "SI", "iso3": "SVN", "name": "Eslovênia", "formalName": "República da Eslovênia" },
    { "code": "090", "phone": "0677", "iso": "SB", "iso3": "SLB", "name": "Ilhas Salomão", "formalName": "Ilhas Salomão" },
    { "code": "706", "phone": "0252", "iso": "SO", "iso3": "SOM", "name": "Somália", "formalName": "República da Somália" },
    { "code": "710", "phone": "0027", "iso": "ZA", "iso3": "ZAF", "name": "África do Sul", "formalName": "República da África do Sul" },
    { "code": "239", "phone": "0500", "iso": "GS", "iso3": "SGS", "name": "Ilhas Geórgia do Sul e Sandwich do Sul", "formalName": "Ilhas Geórgia do Sul e Sandwich do Sul" },
    { "code": "724", "phone": "0034", "iso": "ES", "iso3": "ESP", "name": "Espanha", "formalName": "Reino da Espanha" },
    { "code": "144", "phone": "0094", "iso": "LK", "iso3": "LKA", "name": "Sri Lanka", "formalName": "República Democrática Socialista do Sri Lanka" },
    { "code": "736", "phone": "0249", "iso": "SD", "iso3": "SDN", "name": "Sudão", "formalName": "República do Sudão" },
    { "code": "740", "phone": "0597", "iso": "SR", "iso3": "SUR", "name": "Suriname", "formalName": "República do Suriname" },
    { "code": "744", "phone": "0047", "iso": "SJ", "iso3": "SJM", "name": "Esvalbarde", "formalName": "Esvalbarde" },
    { "code": "748", "phone": "0268", "iso": "SZ", "iso3": "SWZ", "name": "Suazilândia", "formalName": "Reino da Suazilândia" },
    { "code": "752", "phone": "0046", "iso": "SE", "iso3": "SWE", "name": "Suécia", "formalName": "Reino da Suécia" },
    { "code": "756", "phone": "0041", "iso": "CH", "iso3": "CHE", "name": "Suiça", "formalName": "Confederação Suiça" },
    { "code": "760", "phone": "0963", "iso": "SY", "iso3": "SYR", "name": "Síria", "formalName": "República Árabe Síria" },
    { "code": "158", "phone": "0886", "iso": "TW", "iso3": "TWN", "name": "Taiwan", "formalName": "Taiwan" },
    { "code": "762", "phone": "0992", "iso": "TJ", "iso3": "TJK", "name": "Tajiquistão", "formalName": "República do Tajiquistão" },
    { "code": "834", "phone": "0255", "iso": "TZ", "iso3": "TZA", "name": "Tanzânia", "formalName": "República Unida da Tanzânia" },
    { "code": "764", "phone": "0066", "iso": "TH", "iso3": "THA", "name": "Tailândia", "formalName": "Reino da Tailândia" },
    { "code": "626", "phone": "0670", "iso": "TL", "iso3": "TLS", "name": "Timor-Leste", "formalName": "República Democrática de Timor-Leste" },
    { "code": "768", "phone": "0228", "iso": "TG", "iso3": "TGO", "name": "Togo", "formalName": "República Togolesa" },
    { "code": "772", "phone": "0690", "iso": "TK", "iso3": "TKL", "name": "Toquelau", "formalName": "Toquelau" },
    { "code": "776", "phone": "0676", "iso": "TO", "iso3": "TON", "name": "Tonga", "formalName": "Reino de Tonga" },
    { "code": "780", "phone": "1868", "iso": "TT", "iso3": "TTO", "name": "Trinidad e Tobago", "formalName": "República da Trinidad e Tobago" },
    { "code": "788", "phone": "0216", "iso": "TN", "iso3": "TUN", "name": "Tunísia", "formalName": "República da Tunísia" },
    { "code": "792", "phone": "0090", "iso": "TR", "iso3": "TUR", "name": "Turquia", "formalName": "República da Turquia" },
    { "code": "795", "phone": "7370", "iso": "TM", "iso3": "TKM", "name": "Turcomenistão", "formalName": "Turcomenistão" },
    { "code": "796", "phone": "1649", "iso": "TC", "iso3": "TCA", "name": "Ilhas Turks e Caicos", "formalName": "Ilhas Turks e Caicos" },
    { "code": "798", "phone": "0688", "iso": "TV", "iso3": "TUV", "name": "Tuvalu", "formalName": "Tuvalu" },
    { "code": "800", "phone": "0256", "iso": "UG", "iso3": "UGA", "name": "Uganda", "formalName": "República de Uganda" },
    { "code": "804", "phone": "0380", "iso": "UA", "iso3": "UKR", "name": "Ucrânia", "formalName": "Ucrânia" },
    { "code": "784", "phone": "0971", "iso": "AE", "iso3": "ARE", "name": "Emirados Árabes", "formalName": "Emirados Árabes Unidos" },
    { "code": "826", "phone": "0044", "iso": "GB", "iso3": "GBR", "name": "Reino Unido", "formalName": "Reino Unido da Grã-Bretanha e Irlanda do Norte" },
    { "code": "840", "phone": "0001", "iso": "US", "iso3": "USA", "name": "Estados Unidos", "formalName": "Estados Unidos da América" },
    { "code": "581", "phone": "0001", "iso": "UM", "iso3": "UMI", "name": "Ilhas Menores Distantes dos Estados Unidos", "formalName": "Ilhas Menores Distantes dos Estados Unidos" },
    { "code": "858", "phone": "0598", "iso": "UY", "iso3": "URY", "name": "Uruguai", "formalName": "República Oriental do Uruguai" },
    { "code": "860", "phone": "0998", "iso": "UZ", "iso3": "UZB", "name": "Uzbequistão", "formalName": "República do Uzbequistão" },
    { "code": "548", "phone": "0678", "iso": "VU", "iso3": "VUT", "name": "Vanuatu", "formalName": "República de Vanuatu" },
    { "code": "862", "phone": "0058", "iso": "VE", "iso3": "VEN", "name": "Venezuela", "formalName": "República Bolivariana da Venezuela" },
    { "code": "704", "phone": "0084", "iso": "VN", "iso3": "VNM", "name": "Vietnam", "formalName": "República Socialista do Vietnam" },
    { "code": "092", "phone": "1284", "iso": "VG", "iso3": "VGB", "name": "Ilhas Virgens Inglesas", "formalName": "Ilhas Virgens" },
    { "code": "850", "phone": "1340", "iso": "VI", "iso3": "VIR", "name": "Ilhas Virgens (USA)", "formalName": "Ilhas Virgens dos Estados Unidos" },
    { "code": "876", "phone": "0681", "iso": "WF", "iso3": "WLF", "name": "Wallis e Futuna", "formalName": "Wallis e Futuna" },
    { "code": "732", "phone": "0212", "iso": "EH", "iso3": "ESH", "name": "Saara Ocidental", "formalName": "Saara Ocidental" },
    { "code": "887", "phone": "0967", "iso": "YE", "iso3": "YEM", "name": "Iêmen", "formalName": "República do Iêmen" },
    { "code": "894", "phone": "0260", "iso": "ZM", "iso3": "ZMB", "name": "Zâmbia", "formalName": "República do Zâmbia" },
    { "code": "716", "phone": "0263", "iso": "ZW", "iso3": "ZWE", "name": "Zimbábue", "formalName": "República do Zimbábue" }
]

addCountries()